export const FETCH_DATA = "FETCH_DATA";
export const ADD_EMPLOYEE_DATA = "ADD_EMPLOYEE_DATA";
export const DELETE_EMPLOYEE_DATA = "DELETE_EMPLOYEE_DATA"
export const RESET_ALL_DATA = "RESET_ALL_DATA"
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE"