export const employees = [
  {
    id: 1,
    first_name: "Karly",
    last_name: "Kmieciak",
    email: "kkmieciak0@live.com",
    sex: "Female",
    address: "0279 Dottie Plaza",
    phone: "2797523241",
    DOB: "2021-09-08",
    designation: "Software Consultant",
  },
  {
    id: 2,
    first_name: "Nickolas",
    last_name: "Pearse",
    email: "npearse1@dell.com",
    sex: "Male",
    address: "736 Ohio Trail",
    phone: "3579011430",
    DOB: "2022-03-24",
    designation: "Financial Analyst",
  },
  {
    id: 3,
    first_name: "Rickey",
    last_name: "Dudson",
    email: "rdudson2@timesonline.co.uk",
    sex: "Male",
    address: "20 Lakewood Drive",
    phone: "7312206471",
    DOB: "2022-02-15",
    designation: "Account Executive",
  },
  {
    id: 4,
    first_name: "Alfreda",
    last_name: "Pimmocke",
    email: "apimmocke3@shinystat.com",
    sex: "Female",
    address: "7820 Schlimgen Crossing",
    phone: "9551451025",
    DOB: "2021-07-27",
    designation: "Human Resources Assistant IV",
  },
  {
    id: 5,
    first_name: "Amii",
    last_name: "Simon",
    email: "asimon4@prnewswire.com",
    sex: "Female",
    address: "7133 Roxbury Circle",
    phone: "8486604954",
    DOB: "2021-09-03",
    designation: "Professor",
  },
  {
    id: 6,
    first_name: "Tiphani",
    last_name: "Ladel",
    email: "tladel5@phpbb.com",
    sex: "Polygender",
    address: "9 East Avenue",
    phone: "9008450662",
    DOB: "2021-06-06",
    designation: "Mechanical Systems Engineer",
  },
  {
    id: 7,
    first_name: "Arin",
    last_name: "Pryer",
    email: "apryer6@bluehost.com",
    sex: "Non-binary",
    address: "94 Loftsgordon Street",
    phone: "5881179246",
    DOB: "2021-06-25",
    designation: "Registered Nurse",
  },
  {
    id: 8,
    first_name: "Cullen",
    last_name: "Twelves",
    email: "ctwelves7@wunderground.com",
    sex: "Male",
    address: "98797 Logan Alley",
    phone: "4948119387",
    DOB: "2021-04-23",
    designation: "Marketing Manager",
  },
  {
    id: 9,
    first_name: "Tirrell",
    last_name: "Mapson",
    email: "tmapson8@elegantthemes.com",
    sex: "Male",
    address: "38 Dorton Hill",
    phone: "5765797179",
    DOB: "2022-03-15",
    designation: "Systems Administrator II",
  },
  {
    id: 10,
    first_name: "Winny",
    last_name: "Mowday",
    email: "wmowday9@examiner.com",
    sex: "Male",
    address: "945 Clarendon Hill",
    phone: "1783873188",
    DOB: "2021-11-28",
    designation: "Research Nurse",
  },
  {
    id: 11,
    first_name: "Salim",
    last_name: "Bathow",
    email: "sbathowa@google.ca",
    sex: "Male",
    address: "3602 North Pass",
    phone: "2058749703",
    DOB: "2021-04-28",
    designation: "Internal Auditor",
  },
  {
    id: 12,
    first_name: "Kort",
    last_name: "Jouanny",
    email: "kjouannyb@plala.or.jp",
    sex: "Male",
    address: "006 Heffernan Court",
    phone: "8253204067",
    DOB: "2021-11-08",
    designation: "Account Coordinator",
  },
  {
    id: 13,
    first_name: "Colver",
    last_name: "Pedri",
    email: "cpedric@cisco.com",
    sex: "Male",
    address: "788 Packers Center",
    phone: "7723160389",
    DOB: "2021-12-20",
    designation: "Executive Secretary",
  },
  {
    id: 14,
    first_name: "Laurette",
    last_name: "Yakovl",
    email: "lyakovld@foxnews.com",
    sex: "Female",
    address: "315 Shasta Parkway",
    phone: "1801980534",
    DOB: "2021-11-10",
    designation: "Research Assistant III",
  },
  {
    id: 15,
    first_name: "Lorilyn",
    last_name: "Upstell",
    email: "lupstelle@moonfruit.com",
    sex: "Bigender",
    address: "08432 Summer Ridge Plaza",
    phone: "9179264609",
    DOB: "2021-11-19",
    designation: "Environmental Specialist",
  },
  {
    id: 16,
    first_name: "Melesa",
    last_name: "Ollin",
    email: "mollinf@bravesites.com",
    sex: "Female",
    address: "777 Monica Park",
    phone: "1698049435",
    DOB: "2021-12-07",
    designation: "Automation Specialist II",
  },
  {
    id: 17,
    first_name: "Hyatt",
    last_name: "Moreno",
    email: "hmorenog@opensource.org",
    sex: "Male",
    address: "60095 Longview Crossing",
    phone: "4079870032",
    DOB: "2021-11-10",
    designation: "GIS Technical Architect",
  },
  {
    id: 18,
    first_name: "Porty",
    last_name: "Gregori",
    email: "pgregorih@sciencedaily.com",
    sex: "Male",
    address: "4 Sommers Place",
    phone: "3883576811",
    DOB: "2022-02-21",
    designation: "VP Accounting",
  },
  {
    id: 19,
    first_name: "Daffi",
    last_name: "Humbatch",
    email: "dhumbatchi@weather.com",
    sex: "Female",
    address: "95 Helena Point",
    phone: "2738874722",
    DOB: "2021-06-28",
    designation: "Help Desk Operator",
  },
  {
    id: 20,
    first_name: "Fredek",
    last_name: "Struys",
    email: "fstruysj@ovh.net",
    sex: "Male",
    address: "4445 West Road",
    phone: "2482942488",
    DOB: "2021-05-31",
    designation: "Quality Control Specialist",
  },
  {
    id: 21,
    first_name: "Karly",
    last_name: "Kmieciak",
    email: "kkmieciak0@live.com",
    sex: "Female",
    address: "0279 Dottie Plaza",
    phone: "2797523241",
    DOB: "2021-09-08",
    designation: "Software Consultant",
  },
  {
    id: 22,
    first_name: "Nickolas",
    last_name: "Pearse",
    email: "npearse1@dell.com",
    sex: "Male",
    address: "736 Ohio Trail",
    phone: "3579011430",
    DOB: "2022-03-24",
    designation: "Financial Analyst",
  },
  {
    id: 23,
    first_name: "Rickey",
    last_name: "Dudson",
    email: "rdudson2@timesonline.co.uk",
    sex: "Male",
    address: "20 Lakewood Drive",
    phone: "7312206471",
    DOB: "2022-02-15",
    designation: "Account Executive",
  },
  {
    id: 24,
    first_name: "Alfreda",
    last_name: "Pimmocke",
    email: "apimmocke3@shinystat.com",
    sex: "Female",
    address: "7820 Schlimgen Crossing",
    phone: "9551451025",
    DOB: "2021-07-27",
    designation: "Human Resources Assistant IV",
  },
  {
    id: 25,
    first_name: "Amii",
    last_name: "Simon",
    email: "asimon4@prnewswire.com",
    sex: "Female",
    address: "7133 Roxbury Circle",
    phone: "8486604954",
    DOB: "2021-09-03",
    designation: "Professor",
  },
  {
    id: 26,
    first_name: "Tiphani",
    last_name: "Ladel",
    email: "tladel5@phpbb.com",
    sex: "Polygender",
    address: "9 East Avenue",
    phone: "9008450662",
    DOB: "2021-06-06",
    designation: "Mechanical Systems Engineer",
  },
  {
    id: 27,
    first_name: "Arin",
    last_name: "Pryer",
    email: "apryer6@bluehost.com",
    sex: "Non-binary",
    address: "94 Loftsgordon Street",
    phone: "5881179246",
    DOB: "2021-06-25",
    designation: "Registered Nurse",
  },
  {
    id: 28,
    first_name: "Cullen",
    last_name: "Twelves",
    email: "ctwelves7@wunderground.com",
    sex: "Male",
    address: "98797 Logan Alley",
    phone: "4948119387",
    DOB: "2021-04-23",
    designation: "Marketing Manager",
  },
  {
    id: 29,
    first_name: "Tirrell",
    last_name: "Mapson",
    email: "tmapson8@elegantthemes.com",
    sex: "Male",
    address: "38 Dorton Hill",
    phone: "5765797179",
    DOB: "2022-03-15",
    designation: "Systems Administrator II",
  },
  {
    id: 30,
    first_name: "Winny",
    last_name: "Mowday",
    email: "wmowday9@examiner.com",
    sex: "Male",
    address: "945 Clarendon Hill",
    phone: "1783873188",
    DOB: "2021-11-28",
    designation: "Research Nurse",
  },
  {
    id: 31,
    first_name: "Salim",
    last_name: "Bathow",
    email: "sbathowa@google.ca",
    sex: "Male",
    address: "3602 North Pass",
    phone: "2058749703",
    DOB: "2021-04-28",
    designation: "Internal Auditor",
  },
  {
    id: 32,
    first_name: "Kort",
    last_name: "Jouanny",
    email: "kjouannyb@plala.or.jp",
    sex: "Male",
    address: "006 Heffernan Court",
    phone: "8253204067",
    DOB: "2021-11-08",
    designation: "Account Coordinator",
  },
  {
    id: 33,
    first_name: "Colver",
    last_name: "Pedri",
    email: "cpedric@cisco.com",
    sex: "Male",
    address: "788 Packers Center",
    phone: "7723160389",
    DOB: "2021-12-20",
    designation: "Executive Secretary",
  },
  {
    id: 34,
    first_name: "Laurette",
    last_name: "Yakovl",
    email: "lyakovld@foxnews.com",
    sex: "Female",
    address: "315 Shasta Parkway",
    phone: "1801980534",
    DOB: "2021-11-10",
    designation: "Research Assistant III",
  },
  {
    id: 35,
    first_name: "Lorilyn",
    last_name: "Upstell",
    email: "lupstelle@moonfruit.com",
    sex: "Bigender",
    address: "08432 Summer Ridge Plaza",
    phone: "9179264609",
    DOB: "2021-11-19",
    designation: "Environmental Specialist",
  },
  {
    id: 36,
    first_name: "Melesa",
    last_name: "Ollin",
    email: "mollinf@bravesites.com",
    sex: "Female",
    address: "777 Monica Park",
    phone: "1698049435",
    DOB: "2021-12-07",
    designation: "Automation Specialist II",
  },
  {
    id: 37,
    first_name: "Hyatt",
    last_name: "Moreno",
    email: "hmorenog@opensource.org",
    sex: "Male",
    address: "60095 Longview Crossing",
    phone: "4079870032",
    DOB: "2021-11-10",
    designation: "GIS Technical Architect",
  },
  {
    id: 38,
    first_name: "Porty",
    last_name: "Gregori",
    email: "pgregorih@sciencedaily.com",
    sex: "Male",
    address: "4 Sommers Place",
    phone: "3883576811",
    DOB: "2022-02-21",
    designation: "VP Accounting",
  },
  {
    id: 39,
    first_name: "Daffi",
    last_name: "Humbatch",
    email: "dhumbatchi@weather.com",
    sex: "Female",
    address: "95 Helena Point",
    phone: "2738874722",
    DOB: "2021-06-28",
    designation: "Help Desk Operator",
  },
  {
    id: 40,
    first_name: "Fredek",
    last_name: "Struys",
    email: "fstruysj@ovh.net",
    sex: "Male",
    address: "4445 West Road",
    phone: "2482942488",
    DOB: "2021-05-31",
    designation: "Quality Control Specialist",
  },
  {
    id: 41,
    first_name: "Karly",
    last_name: "Kmieciak",
    email: "kkmieciak0@live.com",
    sex: "Female",
    address: "0279 Dottie Plaza",
    phone: "2797523241",
    DOB: "2021-09-08",
    designation: "Software Consultant",
  },
  {
    id: 42,
    first_name: "Nickolas",
    last_name: "Pearse",
    email: "npearse1@dell.com",
    sex: "Male",
    address: "736 Ohio Trail",
    phone: "3579011430",
    DOB: "2022-03-24",
    designation: "Financial Analyst",
  },
  {
    id: 43,
    first_name: "Rickey",
    last_name: "Dudson",
    email: "rdudson2@timesonline.co.uk",
    sex: "Male",
    address: "20 Lakewood Drive",
    phone: "7312206471",
    DOB: "2022-02-15",
    designation: "Account Executive",
  },
  {
    id: 44,
    first_name: "Alfreda",
    last_name: "Pimmocke",
    email: "apimmocke3@shinystat.com",
    sex: "Female",
    address: "7820 Schlimgen Crossing",
    phone: "9551451025",
    DOB: "2021-07-27",
    designation: "Human Resources Assistant IV",
  },
  {
    id: 45,
    first_name: "Amii",
    last_name: "Simon",
    email: "asimon4@prnewswire.com",
    sex: "Female",
    address: "7133 Roxbury Circle",
    phone: "8486604954",
    DOB: "2021-09-03",
    designation: "Professor",
  },
  {
    id: 46,
    first_name: "Tiphani",
    last_name: "Ladel",
    email: "tladel5@phpbb.com",
    sex: "Polygender",
    address: "9 East Avenue",
    phone: "9008450662",
    DOB: "2021-06-06",
    designation: "Mechanical Systems Engineer",
  },
  {
    id: 47,
    first_name: "Arin",
    last_name: "Pryer",
    email: "apryer6@bluehost.com",
    sex: "Non-binary",
    address: "94 Loftsgordon Street",
    phone: "5881179246",
    DOB: "2021-06-25",
    designation: "Registered Nurse",
  },
  {
    id: 48,
    first_name: "Cullen",
    last_name: "Twelves",
    email: "ctwelves7@wunderground.com",
    sex: "Male",
    address: "98797 Logan Alley",
    phone: "4948119387",
    DOB: "2021-04-23",
    designation: "Marketing Manager",
  },
  {
    id: 49,
    first_name: "Tirrell",
    last_name: "Mapson",
    email: "tmapson8@elegantthemes.com",
    sex: "Male",
    address: "38 Dorton Hill",
    phone: "5765797179",
    DOB: "2022-03-15",
    designation: "Systems Administrator II",
  },
  {
    id: 50,
    first_name: "Winny",
    last_name: "Mowday",
    email: "wmowday9@examiner.com",
    sex: "Male",
    address: "945 Clarendon Hill",
    phone: "1783873188",
    DOB: "2021-11-28",
    designation: "Research Nurse",
  },
  {
    id: 51,
    first_name: "Salim",
    last_name: "Bathow",
    email: "sbathowa@google.ca",
    sex: "Male",
    address: "3602 North Pass",
    phone: "2058749703",
    DOB: "2021-04-28",
    designation: "Internal Auditor",
  },
  {
    id: 52,
    first_name: "Kort",
    last_name: "Jouanny",
    email: "kjouannyb@plala.or.jp",
    sex: "Male",
    address: "006 Heffernan Court",
    phone: "8253204067",
    DOB: "2021-11-08",
    designation: "Account Coordinator",
  },
  {
    id: 53,
    first_name: "Colver",
    last_name: "Pedri",
    email: "cpedric@cisco.com",
    sex: "Male",
    address: "788 Packers Center",
    phone: "7723160389",
    DOB: "2021-12-20",
    designation: "Executive Secretary",
  },
  {
    id: 54,
    first_name: "Laurette",
    last_name: "Yakovl",
    email: "lyakovld@foxnews.com",
    sex: "Female",
    address: "315 Shasta Parkway",
    phone: "1801980534",
    DOB: "2021-11-10",
    designation: "Research Assistant III",
  },
  {
    id: 55,
    first_name: "Lorilyn",
    last_name: "Upstell",
    email: "lupstelle@moonfruit.com",
    sex: "Bigender",
    address: "08432 Summer Ridge Plaza",
    phone: "9179264609",
    DOB: "2021-11-19",
    designation: "Environmental Specialist",
  },
  {
    id: 56,
    first_name: "Melesa",
    last_name: "Ollin",
    email: "mollinf@bravesites.com",
    sex: "Female",
    address: "777 Monica Park",
    phone: "1698049435",
    DOB: "2021-12-07",
    designation: "Automation Specialist II",
  },
  {
    id: 57,
    first_name: "Hyatt",
    last_name: "Moreno",
    email: "hmorenog@opensource.org",
    sex: "Male",
    address: "60095 Longview Crossing",
    phone: "4079870032",
    DOB: "2021-11-10",
    designation: "GIS Technical Architect",
  },
  {
    id: 58,
    first_name: "Porty",
    last_name: "Gregori",
    email: "pgregorih@sciencedaily.com",
    sex: "Male",
    address: "4 Sommers Place",
    phone: "3883576811",
    DOB: "2022-02-21",
    designation: "VP Accounting",
  },
  {
    id: 59,
    first_name: "Daffi",
    last_name: "Humbatch",
    email: "dhumbatchi@weather.com",
    sex: "Female",
    address: "95 Helena Point",
    phone: "2738874722",
    DOB: "2021-06-28",
    designation: "Help Desk Operator",
  },
  {
    id: 60,
    first_name: "Fredek",
    last_name: "Struys",
    email: "fstruysj@ovh.net",
    sex: "Male",
    address: "4445 West Road",
    phone: "2482942488",
    DOB: "2021-05-31",
    designation: "Quality Control Specialist",
  },
  {
    id: 61,
    first_name: "Karly",
    last_name: "Kmieciak",
    email: "kkmieciak0@live.com",
    sex: "Female",
    address: "0279 Dottie Plaza",
    phone: "2797523241",
    DOB: "2021-09-08",
    designation: "Software Consultant",
  },
  {
    id: 62,
    first_name: "Nickolas",
    last_name: "Pearse",
    email: "npearse1@dell.com",
    sex: "Male",
    address: "736 Ohio Trail",
    phone: "3579011430",
    DOB: "2022-03-24",
    designation: "Financial Analyst",
  },
  {
    id: 63,
    first_name: "Rickey",
    last_name: "Dudson",
    email: "rdudson2@timesonline.co.uk",
    sex: "Male",
    address: "20 Lakewood Drive",
    phone: "7312206471",
    DOB: "2022-02-15",
    designation: "Account Executive",
  },
  {
    id: 64,
    first_name: "Alfreda",
    last_name: "Pimmocke",
    email: "apimmocke3@shinystat.com",
    sex: "Female",
    address: "7820 Schlimgen Crossing",
    phone: "9551451025",
    DOB: "2021-07-27",
    designation: "Human Resources Assistant IV",
  },
  {
    id: 65,
    first_name: "Amii",
    last_name: "Simon",
    email: "asimon4@prnewswire.com",
    sex: "Female",
    address: "7133 Roxbury Circle",
    phone: "8486604954",
    DOB: "2021-09-03",
    designation: "Professor",
  },
  {
    id: 66,
    first_name: "Tiphani",
    last_name: "Ladel",
    email: "tladel5@phpbb.com",
    sex: "Polygender",
    address: "9 East Avenue",
    phone: "9008450662",
    DOB: "2021-06-06",
    designation: "Mechanical Systems Engineer",
  },
  {
    id: 67,
    first_name: "Arin",
    last_name: "Pryer",
    email: "apryer6@bluehost.com",
    sex: "Non-binary",
    address: "94 Loftsgordon Street",
    phone: "5881179246",
    DOB: "2021-06-25",
    designation: "Registered Nurse",
  },
  {
    id: 68,
    first_name: "Cullen",
    last_name: "Twelves",
    email: "ctwelves7@wunderground.com",
    sex: "Male",
    address: "98797 Logan Alley",
    phone: "4948119387",
    DOB: "2021-04-23",
    designation: "Marketing Manager",
  },
  {
    id: 69,
    first_name: "Tirrell",
    last_name: "Mapson",
    email: "tmapson8@elegantthemes.com",
    sex: "Male",
    address: "38 Dorton Hill",
    phone: "5765797179",
    DOB: "2022-03-15",
    designation: "Systems Administrator II",
  },
  {
    id: 70,
    first_name: "Winny",
    last_name: "Mowday",
    email: "wmowday9@examiner.com",
    sex: "Male",
    address: "945 Clarendon Hill",
    phone: "1783873188",
    DOB: "2021-11-28",
    designation: "Research Nurse",
  },
  {
    id: 71,
    first_name: "Salim",
    last_name: "Bathow",
    email: "sbathowa@google.ca",
    sex: "Male",
    address: "3602 North Pass",
    phone: "2058749703",
    DOB: "2021-04-28",
    designation: "Internal Auditor",
  },
  {
    id: 72,
    first_name: "Kort",
    last_name: "Jouanny",
    email: "kjouannyb@plala.or.jp",
    sex: "Male",
    address: "006 Heffernan Court",
    phone: "8253204067",
    DOB: "2021-11-08",
    designation: "Account Coordinator",
  },
  {
    id: 73,
    first_name: "Colver",
    last_name: "Pedri",
    email: "cpedric@cisco.com",
    sex: "Male",
    address: "788 Packers Center",
    phone: "7723160389",
    DOB: "2021-12-20",
    designation: "Executive Secretary",
  },
  {
    id: 74,
    first_name: "Laurette",
    last_name: "Yakovl",
    email: "lyakovld@foxnews.com",
    sex: "Female",
    address: "315 Shasta Parkway",
    phone: "1801980534",
    DOB: "2021-11-10",
    designation: "Research Assistant III",
  },
  {
    id: 75,
    first_name: "Lorilyn",
    last_name: "Upstell",
    email: "lupstelle@moonfruit.com",
    sex: "Bigender",
    address: "08432 Summer Ridge Plaza",
    phone: "9179264609",
    DOB: "2021-11-19",
    designation: "Environmental Specialist",
  },
  {
    id: 76,
    first_name: "Melesa",
    last_name: "Ollin",
    email: "mollinf@bravesites.com",
    sex: "Female",
    address: "777 Monica Park",
    phone: "1698049435",
    DOB: "2021-12-07",
    designation: "Automation Specialist II",
  },
  {
    id: 77,
    first_name: "Hyatt",
    last_name: "Moreno",
    email: "hmorenog@opensource.org",
    sex: "Male",
    address: "60095 Longview Crossing",
    phone: "4079870032",
    DOB: "2021-11-10",
    designation: "GIS Technical Architect",
  },
  {
    id: 78,
    first_name: "Porty",
    last_name: "Gregori",
    email: "pgregorih@sciencedaily.com",
    sex: "Male",
    address: "4 Sommers Place",
    phone: "3883576811",
    DOB: "2022-02-21",
    designation: "VP Accounting",
  },
  {
    id: 79,
    first_name: "Daffi",
    last_name: "Humbatch",
    email: "dhumbatchi@weather.com",
    sex: "Female",
    address: "95 Helena Point",
    phone: "2738874722",
    DOB: "2021-06-28",
    designation: "Help Desk Operator",
  },
  {
    id: 80,
    first_name: "Fredek",
    last_name: "Struys",
    email: "fstruysj@ovh.net",
    sex: "Male",
    address: "4445 West Road",
    phone: "2482942488",
    DOB: "2021-05-31",
    designation: "Quality Control Specialist",
  }
];
