const arr = [
  {
    id: 1,
    first_name: "Roi",
    last_name: "Caughte",
    email: "rcaughte0@slashdot.org",
    sex: "Male",
    address: "55 Erie Trail",
    phone: "4435547246",
    designation: "Nurse Practicioner",
  },
  {
    id: 2,
    first_name: "Lin",
    last_name: "Gamon",
    email: "lgamon1@freewebs.com",
    sex: "Genderfluid",
    address: "33842 Hoard Point",
    phone: "8853806533",
    designation: "Dental Hygienist",
  },
  {
    id: 3,
    first_name: "Melody",
    last_name: "Briffett",
    email: "mbriffett2@ft.com",
    sex: "Female",
    address: "168 Raven Trail",
    phone: "8539954923",
    designation: "Professor",
  },
  {
    id: 4,
    first_name: "Carol",
    last_name: "Gresswell",
    email: "cgresswell3@arstechnica.com",
    sex: "Female",
    address: "364 Blackbird Center",
    phone: "5157142773",
    designation: "Assistant Professor",
  },
  {
    id: 5,
    first_name: "Caresa",
    last_name: "Seedhouse",
    email: "cseedhouse4@blogspot.com",
    sex: "Female",
    address: "05 Melby Parkway",
    phone: "3261302154",
    designation: "Environmental Specialist",
  },
  {
    id: 6,
    first_name: "Hanson",
    last_name: "Harbar",
    email: "hharbar5@umn.edu",
    sex: "Male",
    address: "932 Springview Plaza",
    phone: "8872186381",
    designation: "Dental Hygienist",
  },
  {
    id: 7,
    first_name: "Dore",
    last_name: "Tomczykiewicz",
    email: "dtomczykiewicz6@cam.ac.uk",
    sex: "Female",
    address: "75 Beilfuss Parkway",
    phone: "7341098943",
    designation: "Nuclear Power Engineer",
  },
  {
    id: 8,
    first_name: "Vickie",
    last_name: "Suerz",
    email: "vsuerz7@wikimedia.org",
    sex: "Female",
    address: "6746 Stephen Pass",
    phone: "8643925468",
    designation: "Community Outreach Specialist",
  },
  {
    id: 9,
    first_name: "Myron",
    last_name: "Waddilove",
    email: "mwaddilove8@upenn.edu",
    sex: "Male",
    address: "126 Kennedy Hill",
    phone: "7869667240",
    designation: "Help Desk Technician",
  },
  {
    id: 10,
    first_name: "Nolana",
    last_name: "Greystoke",
    email: "ngreystoke9@java.com",
    sex: "Female",
    address: "290 Kensington Court",
    phone: "8575950291",
    designation: "Chemical Engineer",
  },
  {
    id: 11,
    first_name: "Karlens",
    last_name: "Tardiff",
    email: "ktardiffa@cbc.ca",
    sex: "Male",
    address: "17239 Knutson Way",
    phone: "4266744309",
    designation: "Speech Pathologist",
  },
  {
    id: 12,
    first_name: "Reinhard",
    last_name: "Elstone",
    email: "relstoneb@webnode.com",
    sex: "Male",
    address: "124 Atwood Hill",
    phone: "3871740572",
    designation: "Biostatistician IV",
  },
  {
    id: 13,
    first_name: "Lanny",
    last_name: "Keighley",
    email: "lkeighleyc@businessinsider.com",
    sex: "Male",
    address: "751 Crescent Oaks Street",
    phone: "9765008983",
    designation: "Assistant Media Planner",
  },
  {
    id: 14,
    first_name: "Claresta",
    last_name: "Baike",
    email: "cbaiked@usa.gov",
    sex: "Bigender",
    address: "13 Starling Lane",
    phone: "2846972410",
    designation: "Librarian",
  },
  {
    id: 15,
    first_name: "Eada",
    last_name: "McGurk",
    email: "emcgurke@java.com",
    sex: "Female",
    address: "8118 Spenser Center",
    phone: "6768655473",
    designation: "Recruiting Manager",
  },
  {
    id: 16,
    first_name: "Christel",
    last_name: "Barbery",
    email: "cbarberyf@japanpost.jp",
    sex: "Female",
    address: "4109 Lyons Park",
    phone: "4857013619",
    designation: "Software Test Engineer II",
  },
  {
    id: 17,
    first_name: "Carlye",
    last_name: "Scrivinor",
    email: "cscrivinorg@dmoz.org",
    sex: "Female",
    address: "21 John Wall Center",
    phone: "4231873685",
    designation: "Civil Engineer",
  },
  {
    id: 18,
    first_name: "Graham",
    last_name: "MacLaren",
    email: "gmaclarenh@sfgate.com",
    sex: "Male",
    address: "7255 Armistice Pass",
    phone: "1175444745",
    designation: "Physical Therapy Assistant",
  },
  {
    id: 19,
    first_name: "Elisha",
    last_name: "Biesinger",
    email: "ebiesingeri@sonet.ne.jp",
    sex: "Female",
    address: "3 Buena Vista Place",
    phone: "5359609251",
    designation: "Media Manager III",
  },
  {
    id: 20,
    first_name: "Junette",
    last_name: "Sunter",
    email: "jsunterj@liveinternet.ru",
    sex: "Female",
    address: "5109 Bunting Avenue",
    phone: "9685414453",
    designation: "Account Executive",
  },
  {
    id: 21,
    first_name: "Giustino",
    last_name: "Duxbarry",
    email: "gduxbarryk@cnn.com",
    sex: "Male",
    address: "4336 Artisan Hill",
    phone: "6059331598",
    designation: "Nurse",
  },
  {
    id: 22,
    first_name: "Winfred",
    last_name: "Maase",
    email: "wmaasel@reference.com",
    sex: "Male",
    address: "41 Banding Park",
    phone: "7449556901",
    designation: "Compensation Analyst",
  },
  {
    id: 23,
    first_name: "Hilarius",
    last_name: "Silversmid",
    email: "hsilversmidm@gizmodo.com",
    sex: "Male",
    address: "51530 Dorton Lane",
    phone: "4022404961",
    designation: "Web Developer III",
  },
  {
    id: 24,
    first_name: "Annalee",
    last_name: "Scrange",
    email: "ascrangen@parallels.com",
    sex: "Female",
    address: "03 Holy Cross Park",
    phone: "9564782169",
    designation: "Civil Engineer",
  },
  {
    id: 25,
    first_name: "Lauraine",
    last_name: "Mattaser",
    email: "lmattasero@ucsd.edu",
    sex: "Female",
    address: "575 Old Gate Street",
    phone: "7901209918",
    designation: "Project Manager",
  },
];
